export enum InvoiceStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  INSURANCE_PENDING = 'INSURANCE_PENDING',
  INSURANCE_REJECTED = 'INSURANCE_REJECTED',
  INSURANCE_APPROVED = 'INSURANCE_APPROVED',
}
