export enum ReportType {
  REVENUE = 'REVENUE',
  EXPENSES = 'EXPENSES',
  PROFIT_LOSS = 'PROFIT_LOSS',
  ACCOUNTS_RECEIVABLE = 'ACCOUNTS_RECEIVABLE',
  INSURANCE_CLAIMS = 'INSURANCE_CLAIMS',
  DEPARTMENT_PERFORMANCE = 'DEPARTMENT_PERFORMANCE',
  SERVICE_PERFORMANCE = 'SERVICE_PERFORMANCE',
  PAYMENT_ANALYTICS = 'PAYMENT_ANALYTICS',
  COMPREHENSIVE = 'COMPREHENSIVE',
}
