/**
 * Enum for different types of medical appointments
 */
export enum AppointmentType {
  ROUTINE = 'ROUTINE',
  URGENT = 'URGENT',
  EMERGENCY = 'EMERGENCY',
  FOLLOW_UP = 'FOLLOW_UP',
  SPECIALIST = 'SPECIALIST',
  TELEMEDICINE = 'TELEMEDICINE',
  PROCEDURE = 'PROCEDURE',
  DIAGNOSTIC = 'DIAGNOSTIC',
  VACCINATION = 'VACCINATION',
  WELLNESS = 'WELLNESS',
  CONSULTATION = 'CONSULTATION',
  THERAPY = 'THERAPY',
  SCREENING = 'SCREENING',
}
