export enum EducationType {
  CME = 'CME', // Continuing Medical Education
  CONFERENCE = 'CONFERENCE',
  WORKSHOP = 'WORKSHOP',
  CERTIFICATION = 'CERTIFICATION',
  TRAINING = 'TRAINING',
  SEMINAR = 'SEMINAR',
  WEBINAR = 'WEBINAR',
  RESEARCH = 'RESEARCH',
  PUBLICATION = 'PUBLICATION',
  TEACHING = 'TEACHING',
}
