export enum MetricType {
  PATIENT_SATISFACTION = 'PATIENT_SATISFACTION',
  TREATMENT_SUCCESS_RATE = 'TREATMENT_SUCCESS_RATE',
  CONSULTATION_TIME = 'CONSULTATION_TIME',
  PATIENT_COUNT = 'PATIENT_COUNT',
  READMISSION_RATE = 'READMISSION_RATE',
  COMPLICATION_RATE = 'COMPLICATION_RATE',
  MORTALITY_RATE = 'MORTALITY_RATE',
  EFFICIENCY_SCORE = 'EFFICIENCY_SCORE',
  QUALITY_SCORE = 'QUALITY_SCORE',
  PEER_REVIEW_SCORE = 'PEER_REVIEW_SCORE',
}
