export enum ScheduleType {
  APPOINTMENT = "APPOINTMENT",
  SURGERY = "SURGERY",
  CONSULTATION = "CONSULTATION",
  ROUNDS = "ROUNDS",
  ON_CALL = "ON_CALL",
  VACATION = "VACATION",
  SICK_LEAVE = "SICK_LEAVE",
  TRAINING = "TRAINING",
  MEETING = "MEETING",
  EMERGENCY = "EMERGENCY",
}
