export enum UserRole {
  BASIC = 'BASIC',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  ADMIN = 'ADMIN',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  PHARMACIST = 'PHARMACIST',
  MEDICAL_RECORDS = 'MEDICAL_RECORDS',
  EMERGENCY_STAFF = 'EMERGENCY_STAFF',
}
